[project]
name = "python"
version = "1.0.0"
description = "Python example for sending MEI data to the FlowScore server"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "lxml>=6.0.2",
    "websockets>=15.0.1",
    "zeroconf>=0.148.0",
]
